name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
